### ISSUE TITLE
Compatibility Issue with react-stroller and Latest React Version

### ISSUE THREAD

**Issue by AlexKovaliov** [theKashey/React-stroller#9]
Hi there,

We're facing compatibility issues with react-stroller when attempting to update to the latest React version. The current library dependencies are set to an older React version.

Is there a plan to update react-stroller for compatibility with the latest React versions? This would greatly benefit us and other users.

Thanks!

**Comment by theKashey** [comment]
Hey, should not be a problem.

Can you specify what issues you are facing? Not sure there is anything React-18 specific, so if you point me in the right direction that would save some time

**Comment by AlexKovaliov** [comment]
The current "peerDependencies" in react-stroller specify "react": "^16.3.0", causing hindrance to the latest version of React.

**Comment by theKashey** [comment]
👍 this is ease to fix

**Comment by AlexKovaliov** [comment]
Thanks!

**Comment by theKashey** [comment]
Released as v@1.8.1
